language: node_js
node_js: '6'
install: npm install
script:
  - npm run test
  - npm run production
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < doc/coverage/report-lcov/lcov.info
addons:
  code_climate:
    repo_token: e392a2362c6c67c615cb2feeea8fc2020b98bcb31737176592cda37bc51e0bb7
branches:
  only:
    - master
deploy:
  provider: npm
  email: 'info@crazysquirrel.ru'
  api_key: '443206b0-d7ea-47eb-89ca-9ff2e6ec246b'
  skip_cleanup: true
  on:
    branch: master
